<?php

define('NOT_AVI', __('Not Available', 'appointment'));
define('APT_TEXT', __('<b>Note:</b> After creating your desired services, specify the available Date Slot and Time Slot for your services.', 'appointment'));
define('TIMESLOT_HEAD', __('Set Time Slot for', 'appointment'));
define('TIMESLOT_TEXT', __('Add all the Timings for the  Available days i.e. when your services would be available or active.', 'appointment'));
define('DATESLOT_HEAD', __('Set Date Slot for', 'appointment'));
define('DATESLOT_TEXT', __('<b>Note:</b> Set the Opening Date and Closing Date of the service. After that decide the working days of the service. <b>For e.g.</b> If you are running a Spa in summers, then you can choose the Opening Date and Closing Date accordingly and then decide the working days on which your service will be available. If you run your services throughout the year then choose the dates between the entire year range and then choose the days accordingly.', 'appointment'));
define('APT_ADV_SETTING', __('Appointments Advance Settings', 'appointment'));
define('PAYPAL_SETTING', __('Payment Setting', 'appointment'));
define('PAYPAL_CURR', __('Manage Currency', 'appointment'));
define('RP_URL', __('Redirect After Paypal Payment URL', 'appointment'));
define('MERCHANT_ID', __('Merchant ID', 'appointment'));
define('MRC_TITLE_DES', __('Either mention the email id of your Sandbox Testing Mode for testing process or mention the email id of your real PayPal account. For e.g. myaccount@xyz.com', 'appointment'));
define('PYMT_MODE', __('Payment Mode', 'appointment'));
define('PYPL_PYMT_DES', __('<b>Paypal:</b> If you want pay live payment from website i.e. direct payment then you choose this option. Just enter your pay email address and make payment.<br/> <b><a href="https://developer.paypal.com/" target="_blank">PayPal Sandbox :</a></b> If you are going for testing process then you can choose this option. You must have a PayPal Sandbox account setup before using the testing feature.<br/><b>Pay Cash Later:</b> If you want use the service first and pay cash later on then you can choose this option.', 'appointment'));
define('PYPL_OPT', 'Paypal');
define('APT_HEAD', __('Appointment Form Heading', 'appointment'));
define('APT_HEAD_DES', __('Enter your text heading for Appointment Form.', 'appointment'));
define('APT_FIX_HEAD', __('Fix Appointment Heading', 'appointment'));
define('APT_FIX_DES', __('Enter your text heading for Fix Appointment.', 'appointment'));
define('APT_MSG_HEAD', __('Custom Message Heading', 'appointment'));
define('APT_MSG_DES', __('Enter your text heading for Custom Message.', 'appointment'));
define('SAND_OPT', __('Paypal Sandbox', 'appointment'));
define('CASH_OPT', __('Pay Cash Later', 'appointment'));
define('SET_CURR', __('Set Default Currency', 'appointment'));
define('SET_CURR_DES', __('Select Currency code.', 'appointment'));
define('SUP_CURR', __('Supported Currency List', 'appointment'));
define('SAVE_ALL_CHNG', __('Save All Changes', 'appointment'));
//define('FREE_RET_TEXT', 'Your Appointment had been booked. You have to pay the amount of' . $priceshow . '. at the time of appointment.<br/><br/>Thanks');
define('PAYPAL_RET_TEXT', __('<p>Payment is successfully submitted and Your Appointment has been booked. Below are the details of your appointment.</p>', 'appointment'));
define('APT_USF', __('<p>Appointment Booking Unsuccessful.</p><br/><br/>', 'appointment'));
